application: renju-room
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /otf
  static_dir: otf   

- url: .*
  script: main.py
